#Githika Annapureddy
#CruzID: gannapur
#Assignment: pa1

#------------------------------------------------------------------------------
# Makefile for CSE 101 Programming Assignment 1
#
# make                   makes Lex
# make ListTest        makes ListTest
# make clean             removes all binaries
# make checkClient       checks ListTest for memory errors
# make checkLex          checks Lex for memory errors
#------------------------------------------------------------------------------

Lex : Lex.o List.o
	gcc -std=c17 -Wall -o Lex Lex.o List.o

Lex.o : Lex.c List.h
	gcc -std=c17 -Wall -c Lex.c

ListTest: ListTest.o List.o
	gcc -std=c17 -Wall -o ListTest ListTest.o List.o

ListTest.o : ListTest.c List.h
	gcc -std=c17 -Wall -c ListTest.c

List.o : List.c List.h
	gcc -std=c17 -Wall -c List.c

clean :
	rm -f Lex ListTest Lex.o ListTest.o List.o

checkTest : 
	valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s ./ListTest

checkLex :
	valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s ./Lex infile3.txt blah3.txt

